name: flutter_kinescope_sdk
description: Flutter plugin for the Kinescope player.
version: 0.1.5
homepage: https://kinescope.io/
repository: https://github.com/kinescope/flutter-kinescope-player
issue_tracker: https://github.com/kinescope/flutter-kinescope-player/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  surf_lint_rules: ^1.2.0
