name: flutter_kinescope_sdk
description: Flutter plugin for the Kinescope player.
version: 0.1.10
homepage: https://kinescope.io/
repository: https://github.com/kinescope/flutter-kinescope-player
issue_tracker: https://github.com/kinescope/flutter-kinescope-player/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  surf_lint_rules: 3.1.0
